services:
  exiftool-vendored-next-test:
    build:
      target: dev
    restart: always
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3001:3000"
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
